name: discord message
on: [fork, issue_comment, issues, label, merge_group, milestone, project, project_card, project_column, public, pull_request, pull_request_review, pull_request_review_comment, pull_request_target, push, release, status, gollum]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: send custom message with args
      uses: appleboy/discord-action@master
      with:
        webhook_id: ${{ secrets.WEBHOOK_ID }}
        webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
